
using System;
using System.Collections.Generic;

namespace src
{

//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

//Find the sum of all the even-valued terms in the sequence which do not exceed four million.
	public class Problem2
	{
		public void Solve ()
		{
			int answer = 0;
			
			int first = 0;
			int second = 1;
			
			while(answer < 4000000)
			{
				int term = first + second;
				first = second;
				second = term;
				
				if(term % 2 == 0)
					answer += term;
			}

			
			Console.WriteLine("Answer: " + answer);
		}
	}
}
